FLAGS = -r8 -i4 -fast -O4

OBJ = main.o part1.o part2.o matorb.o hamitime.o green.o gear.o util.o \
      diage.o readh.o faster.o\
      eigen.o denmat.o dyn.o tda.o param.o readc.o readp.o \
      smij.o hmij.o subblock.o extrct.o reform.o anlyze.o \
      trans.o aromatic.o backscat.o fixsign.o nadb.o friction.o \
      tsa.o gear2s.o matmat.o ruku.o ruku2s.o
      
bet: 		$(OBJ) makefile
	f77 $(FFLAGS) -o bet $(OBJ) -lblas

main.o:                  main.f makefile

part1.o:                 part1.f makefile

part2.o:                 part2.f makefile

matorb.o:                matorb.f makefile

hamitime.o:              hamitime.f makefile

green.o:                 green.f makefile

gear.o:                  gear.f makefile

util.o:                  util.f makefile

diage.o:                 diage.f makefile

readh.o:                 readh.f makefile

faster.o:                faster.f makefile

eigen.o:                 eigen.f makefile

denmat.o:                denmat.f makefile

dyn.o:                   dyn.f makefile

tda.o:                   tda.f makefile

param.o:                 param.f makefile

readc.o:                 readc.f makefile

readp.o:                 readp.f makefile

smij.o:                  smij.f makefile

hmij.o:                  hmij.f makefile

subblock.o:              subblock.f makefile

extrct.o:                extrct.f makefile

reform.o:                reform.f makefile

anlyze.o:                anlyze.f makefile

trans.o:                 trans.f makefile

aromatic.o:              aromatic.f makefile

backscat.o:              backscat.f makefile

fixsign.o:               fixsign.f makefile

nadb.o:                  nadb.f makefile

friction.o:              friction.f makefile

tsa.o:                   tsa.f makefile

gear2s.o:                gear2s.f makefile

matmat.o:                matmat.f makefile

ruku.o:                  ruku.f makefile

ruku2s.o:                ruku2s.f makefile