#!/bin/csh -f

set dir_of_main  = /home/xie/bet

#check if the directory is correct
set a = `pwd`
if ( $a != $dir_of_main ) then
   echo We are not in the right starting directory!
   exit
endif

@ irun = 0

label_100:

bet_2s < restart_yes


@ irun ++
  
if ( $irun < 150 ) goto label_100 


exit
