#!/bin/csh -f
# script file for md and saving pdb files

#initialize
pwd
date
@ number_of_run = 200
@ length_of_run = 50
@ i0 = 0
@ i = $i0
set dir_of_md = /home/xie/charmm

set a = `pwd`
if ( $a != $dir_of_md ) then
   echo We are not in the right starting directory!
   exit
endif

cd ./azurin/

label_one:

@ i ++

runch < azurin.main

cd
cd ./strk/pdb
if ( -e 1.pdb ) then
   tar -cvf azur.$i.tar *.pdb  
   gzip azur.$i.tar
   mv azur.$i.tar.gz /home/xie/strk/
   rm -f *.pdb
endif   

cd ../../charmm/azurin/

if ( $i - $i0 < $number_of_run ) goto label_one

date
pwd

exit
