FLAGS = -r8 -i4 -fast -O4

OBJ = main.o abort.o aintgs.o alt.o angle.o anlyze.o basis.o bintgs.o \
      bond.o coefft.o coord.o cprint.o delete.o deorth.o deplet.o \
      dihed.o eign.o eigout.o extrct.o fact.o fm3cab.o harmtr.o \
      htype.o huckcl.o intgrl.o jacvec.o load.o match.o matout.o \
      nathyb.o orthog.o prang.o prdist.o pvec.o reform.o relvec.o scf.o \
      scfclo.o scfout.o ss.o stash.o t1.o trans.o aromatic.o util.o \
      fourth.o reformaro.o doublecheck.o cobond.o scfclo1.o lonepair.o \
      fixsign.o
bondo: 		$(OBJ) makefile
	f77 $(FFLAGS) -o bondo $(OBJ)

main.o:                  main.f makefile

abort.o:                 abort.f makefile

aintgs.o:                aintgs.f makefile

alt.o:                   alt.f makefile

angle.o:                 angle.f makefile

anlyze.o:                anlyze.f makefile

basis.o:                 basis.f makefile

bintgs.o:                bintgs.f makefile

bond.o:                  bond.f makefile

coefft.o:                coefft.f makefile

coord.o:                 coord.f makefile

cprint.o:                cprint.f makefile

delete.o:                delete.f makefile

deorth.o:                deorth.f makefile

deplet.o:                deplet.f makefile

dihed.o:                 dihed.f makefile

eign.o:                  eign.f makefile

eigout.o:                eigout.f makefile

extrct.o:                extrct.f makefile

fact.o:                  fact.f makefile

fm3cab.o:                fm3cab.f makefile

harmtr.o:                harmtr.f makefile

htype.o:                 htype.f makefile

huckcl.o:                huckcl.f makefile

intgrl.o:                intgrl.f makefile

jacvec.o:                jacvec.f makefile

load.o:                  load.f makefile

match.o:                 match.f makefile

matout.o:                matout.f makefile

nathyb.o:                nathyb.f makefile

orthog.o:                orthog.f makefile

prang.o:                 prang.f makefile

prdist.o:                prdist.f makefile

pvec.o:                  pvec.f makefile

reform.o:                reform.f makefile

relvec.o:                relvec.f makefile

scf.o:                   scf.f makefile

scfclo.o:                scfclo.f makefile

scfout.o:                scfout.f makefile

ss.o:                    ss.f makefile

stash.o:                 stash.f makefile

t1.o:                    t1.f makefile

trans.o:                 trans.f makefile

aromatic.o:              aromatic.f makefile

util.o:                  util.f makefile

fourth.o:                fourth.f makefile

reformaro.o:             reformaro.f makefile

doublecheck.o:           doublecheck.f makefile

cobond.o:                cobond.f makefile

scfclo1.o:               scfclo1.f makefile

lonepair.o:              lonepair.f makefile

fixsign.o:               fixsign.f makefile